[package]
name = "tudu"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
crossterm = "0.27.0"
dirs = "5.0.1"
hex = "0.4.3"
magic-crypt = "3.1.13"
ratatui = "0.26.3"
rusqlite = { version = "0.31.0", features = ["bundled"] }
